" Generated by vim-plug
<<<<<<< HEAD
" Sat 07 Jul 2018 09:46:23 PM IDT
||||||| merged common ancestors
" Wed 04 Jul 2018 03:49:54 PM IDT
=======
" Thu 05 Jul 2018 12:38:56 PM IDT
>>>>>>> Update
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

<<<<<<< HEAD
silent! let g:plugs['LanguageClient-neovim'].commit = 'f95d2a37a33d'
silent! let g:plugs['ale'].commit = '602e7fa00f50'
||||||| merged common ancestors
silent! let g:plugs['LanguageClient-neovim'].commit = '57ad469568db'
silent! let g:plugs['ale'].commit = '3e8161851107'
=======
silent! let g:plugs['LanguageClient-neovim'].commit = '96079a7e267a'
silent! let g:plugs['ale'].commit = 'e27ec7e13652'
>>>>>>> Update
silent! let g:plugs['ctrlp.vim'].commit = '43cc73b8e7d4'
<<<<<<< HEAD
silent! let g:plugs['delimitMate'].commit = '728b57a6564c'
silent! let g:plugs['deoplete.nvim'].commit = '4cc2041ccfc4'
||||||| merged common ancestors
silent! let g:plugs['delimitMate'].commit = '728b57a6564c'
silent! let g:plugs['deoplete.nvim'].commit = '751d6b3cb6b1'
=======
silent! let g:plugs['delimitMate'].commit = 'b40e2239909a'
silent! let g:plugs['deoplete.nvim'].commit = '751d6b3cb6b1'
>>>>>>> Update
silent! let g:plugs['echodoc.vim'].commit = 'f1f711bc8141'
silent! let g:plugs['fzf'].commit = '6de1ad9d3dd4'
silent! let g:plugs['fzf.vim'].commit = '033033daa391'
silent! let g:plugs['gv.vim'].commit = 'd9b552fbb7de'
silent! let g:plugs['lh-vim-lib'].commit = '43557e8ec48e'
silent! let g:plugs['lightline.vim'].commit = '0532dff598ab'
silent! let g:plugs['local_vimrc'].commit = '7c5236e8865f'
silent! let g:plugs['nerdtree'].commit = 'd6032c876c6d'
silent! let g:plugs['nvim-completion-manager'].commit = '3ef5ade36e73'
silent! let g:plugs['nvim-yarp'].commit = '622cf3981d85'
<<<<<<< HEAD
silent! let g:plugs['rust-doc.vim'].commit = '6d516d2bdffa'
silent! let g:plugs['rust.vim'].commit = 'dfe509828444'
||||||| merged common ancestors
silent! let g:plugs['rust-doc.vim'].commit = '6d516d2bdffa'
silent! let g:plugs['rust.vim'].commit = '0be0e26fbf5f'
=======
silent! let g:plugs['rust-doc.vim'].commit = 'b40e2239909a'
silent! let g:plugs['rust.vim'].commit = '0be0e26fbf5f'
>>>>>>> Update
silent! let g:plugs['sideways.vim'].commit = 'dd5935be01ce'
silent! let g:plugs['tagbar'].commit = '387bbadda98e'
silent! let g:plugs['tlib'].commit = '56c58fd2f907'
silent! let g:plugs['vader.vim'].commit = '49e29404278e'
silent! let g:plugs['vim-addon-mw-utils'].commit = '295862ba6be4'
silent! let g:plugs['vim-commentary'].commit = '7f2127b1dfc5'
silent! let g:plugs['vim-easy-align'].commit = '1cd724dc239c'
silent! let g:plugs['vim-expand-region'].commit = '966513543de0'
silent! let g:plugs['vim-fugitive'].commit = '6f9fa8a4b170'
silent! let g:plugs['vim-gitgutter'].commit = '6076c9678643'
silent! let g:plugs['vim-grepper'].commit = '04d659c9e0a5'
silent! let g:plugs['vim-highlightedyank'].commit = 'eafae05916e6'
silent! let g:plugs['vim-hug-neovim-rpc'].commit = '45080a2180ec'
silent! let g:plugs['vim-linux-coding-style'].commit = '7da66c1b34dc'
silent! let g:plugs['vim-markdown'].commit = '46ba47633f79'
silent! let g:plugs['vim-rooter'].commit = 'abcf7c6e69d5'
silent! let g:plugs['vim-signature'].commit = '6bc3dd1294a2'
silent! let g:plugs['vim-snipmate'].commit = 'a9802f235191'
silent! let g:plugs['vim-snippets'].commit = '6d6cc25570fc'
silent! let g:plugs['vim-surround'].commit = 'aa1f120ad3a2'
silent! let g:plugs['vim-syntax-extra'].commit = 'b60f07799ed9'
silent! let g:plugs['vim-toml'].commit = '85ba8277a6e3'
<<<<<<< HEAD
silent! let g:plugs['vim-trailing-whitespace'].commit = '4c596548216b'
silent! let g:plugs['vimoutliner'].commit = 'aad0a213069b'
||||||| merged common ancestors
silent! let g:plugs['vim-trailing-whitespace'].commit = '4c596548216b'
silent! let g:plugs['vimoutliner'].commit = '4f1262824794'
=======
silent! let g:plugs['vim-trailing-whitespace'].commit = 'b40e2239909a'
silent! let g:plugs['vimoutliner'].commit = 'aad0a213069b'
>>>>>>> Update

PlugUpdate!

