[package]
name = "rex"
version = "0.1.0"
authors = ["Dan Aloni <alonid@gmail.com>"]

[dependencies]
structopt = "0.2.13"
structopt-derive = "0.2.13"
dirs = "1.0.4"
shell-escape = "0.1.4"
ansi_term = "0.11.0"
